export const YYYY_MM_DD_MOMENT_DATE_FORMAT = 'YYYY-MM-DD';
export const YYYY_MM_DD_HH_MM_MOMENT_DATE_FORMAT = 'YYYY-MM-DD HH:mm';
export const HH_MM_MOMENT_TIME_FORMAT = 'HH:mm';
export const FULL_DATE_MOMENT_FORMAT = 'D MMMM YYYY, HH:mm';
